import { TrickMeta } from '@/types';

export const FULL_TRICK_LIBRARY: TrickMeta[] = [
  // --- BASICS & FLATGROUND ---
  {
    name: 'Ollie',
    description: 'The foundation of street skateboarding. Popping the tail and sliding the foot to jump.',
    imageUrl: 'https://picsum.photos/seed/Ollie/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+ollie',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Nollie',
    description: 'Popping an ollie from the nose of the board with your front foot.',
    imageUrl: 'https://picsum.photos/seed/Nollie/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+nollie',
    points: 20,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Fakie Ollie',
    description: 'An ollie performed while riding backwards.',
    imageUrl: 'https://picsum.photos/seed/FakieOllie/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+fakie+ollie',
    points: 15,
    prerequisites: ['Ollie', 'Fakie Riding'],
    isPublic: true,
  },
  {
    name: 'Switch Ollie',
    description: 'An ollie performed in your opposite stance.',
    imageUrl: 'https://picsum.photos/seed/SwitchOllie/600/600',
    difficulty: 'Advanced',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+switch+ollie',
    points: 50,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Boneless',
    description: 'Planting your front foot on the ground to lift the board.',
    imageUrl: 'https://picsum.photos/seed/Boneless/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+boneless',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'No-Comply',
    description: 'Planting your front foot to pop the board, usually with a 180.',
    imageUrl: 'https://picsum.photos/seed/NoComply/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+no+comply',
    points: 20,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Caveman',
    description: 'Holding the board and jumping onto it while in the air.',
    imageUrl: 'https://picsum.photos/seed/Caveman/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+caveman+skate',
    points: 5,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Hippie Jump',
    description: 'Jumping over an obstacle while the board rolls under it.',
    imageUrl: 'https://picsum.photos/seed/HippieJump/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+hippie+jump',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Shove-It',
    description: 'Rotating the board 180 degrees without popping the tail.',
    imageUrl: 'https://picsum.photos/seed/ShoveIt/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+shove+it',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Pop Shove-It',
    description: 'Popping the tail to rotate the board 180 degrees in the air.',
    imageUrl: 'https://picsum.photos/seed/PopShoveIt/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+pop+shove+it',
    points: 20,
    prerequisites: ['Ollie', 'Shove-It'],
    isPublic: true,
  },
  {
    name: 'Frontside Shove-It',
    description: 'Rotating the board 180 degrees frontside (behind you).',
    imageUrl: 'https://picsum.photos/seed/FSShoveIt/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+frontside+shove+it',
    points: 20,
    prerequisites: ['Shove-It'],
    isPublic: true,
  },
  {
    name: 'Bigspin',
    description: 'A 360 shuvit combined with a 180 body varial.',
    imageUrl: 'https://picsum.photos/seed/Bigspin/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+bigspin',
    points: 30,
    prerequisites: ['Pop Shove-It', 'Backside 180'],
    isPublic: true,
  },
  {
    name: 'Frontside 180',
    description: 'Rotating body and board 180 degrees forward.',
    imageUrl: 'https://picsum.photos/seed/FS180/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+frontside+180',
    points: 20,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Backside 180',
    description: 'Rotating body and board 180 degrees backward (blind).',
    imageUrl: 'https://picsum.photos/seed/BS180/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+backside+180',
    points: 25,
    prerequisites: ['Ollie'],
    isPublic: true,
  },

  // --- MANUALS ---
  {
    name: 'Manual',
    description: 'Balancing on the back two wheels.',
    imageUrl: 'https://picsum.photos/seed/Manual/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+manual',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Nose Manual',
    description: 'Balancing on the front two wheels.',
    imageUrl: 'https://picsum.photos/seed/NoseManual/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+nose+manual',
    points: 20,
    prerequisites: ['Manual'],
    isPublic: true,
  },

  // --- FLIP TRICKS ---
  {
    name: 'Kickflip',
    description: 'Flipping the board 360 degrees with the toe.',
    imageUrl: 'https://picsum.photos/seed/Kickflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+kickflip',
    points: 30,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Heelflip',
    description: 'Flipping the board 360 degrees away with the heel.',
    imageUrl: 'https://picsum.photos/seed/Heelflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+heelflip',
    points: 30,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Varial Kickflip',
    description: 'Kickflip combined with a backside shove-it.',
    imageUrl: 'https://picsum.photos/seed/VarialKickflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+varial+kickflip',
    points: 35,
    prerequisites: ['Kickflip', 'Pop Shove-It'],
    isPublic: true,
  },
  {
    name: 'Varial Heelflip',
    description: 'Heelflip combined with a frontside shove-it.',
    imageUrl: 'https://picsum.photos/seed/VarialHeelflip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+varial+heelflip',
    points: 40,
    prerequisites: ['Heelflip', 'Frontside Shove-It'],
    isPublic: true,
  },
  {
    name: 'Hardflip',
    description: 'Frontside pop shove-it with a kickflip.',
    imageUrl: 'https://picsum.photos/seed/Hardflip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+hardflip',
    points: 50,
    prerequisites: ['Kickflip', 'Frontside Shove-It'],
    isPublic: true,
  },
  {
    name: 'Inward Heelflip',
    description: 'Backside pop shove-it with a heelflip.',
    imageUrl: 'https://picsum.photos/seed/InwardHeel/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+inward+heelflip',
    points: 50,
    prerequisites: ['Heelflip', 'Pop Shove-It'],
    isPublic: true,
  },
  {
    name: 'Tre Flip',
    description: '360 shove-it with a kickflip.',
    imageUrl: 'https://picsum.photos/seed/TreFlip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+tre+flip',
    points: 60,
    prerequisites: ['Varial Kickflip', '360 Shove-It'],
    isPublic: true,
  },
  {
    name: 'Laser Flip',
    description: 'Frontside 360 shove-it with a heelflip.',
    imageUrl: 'https://picsum.photos/seed/LaserFlip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+laser+flip',
    points: 70,
    prerequisites: ['Varial Heelflip', 'Frontside 360 Shove-It'],
    isPublic: true,
  },
  {
    name: 'Bigspin Flip',
    description: 'Bigspin combined with a kickflip.',
    imageUrl: 'https://picsum.photos/seed/BigspinFlip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+bigspin+flip',
    points: 65,
    prerequisites: ['Bigspin', 'Kickflip'],
    isPublic: true,
  },
  {
    name: 'Hospital Flip',
    description: 'Half kickflip caught upside down and pulled around.',
    imageUrl: 'https://picsum.photos/seed/HospitalFlip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+hospital+flip',
    points: 55,
    prerequisites: ['Kickflip'],
    isPublic: true,
  },

  // --- GRINDS ---
  {
    name: '50-50 Grind',
    description: 'Grinding on both trucks.',
    imageUrl: 'https://picsum.photos/seed/5050/600/600',
    difficulty: 'Intermediate',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+50-50+grind',
    points: 25,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: '5-0 Grind',
    description: 'Grinding on the back truck only.',
    imageUrl: 'https://picsum.photos/seed/5-0/600/600',
    difficulty: 'Intermediate',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+5-0+grind',
    points: 30,
    prerequisites: ['50-50 Grind', 'Manual'],
    isPublic: true,
  },
  {
    name: 'Nosegrind',
    description: 'Grinding on the front truck only.',
    imageUrl: 'https://picsum.photos/seed/Nosegrind/600/600',
    difficulty: 'Advanced',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+nosegrind',
    points: 40,
    prerequisites: ['50-50 Grind', 'Nose Manual'],
    isPublic: true,
  },
  {
    name: 'Crooked Grind',
    description: 'Grinding on the front truck with the nose angled out.',
    imageUrl: 'https://picsum.photos/seed/Crooked/600/600',
    difficulty: 'Advanced',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+crooked+grind',
    points: 45,
    prerequisites: ['Noseslide'],
    isPublic: true,
  },
  {
    name: 'Smith Grind',
    description: 'Back truck grind with the front of the board dipped down.',
    imageUrl: 'https://picsum.photos/seed/Smith/600/600',
    difficulty: 'Advanced',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+smith+grind',
    points: 45,
    prerequisites: ['5-0 Grind'],
    isPublic: true,
  },
  {
    name: 'Feeble Grind',
    description: 'Back truck grind with the front dipped over the rail.',
    imageUrl: 'https://picsum.photos/seed/Feeble/600/600',
    difficulty: 'Advanced',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+feeble+grind',
    points: 50,
    prerequisites: ['Smith Grind', 'Boardslide'],
    isPublic: true,
  },

  // --- SLIDES ---
  {
    name: 'Boardslide',
    description: 'Sliding the middle of the board over the rail.',
    imageUrl: 'https://picsum.photos/seed/Boardslide/600/600',
    difficulty: 'Easy',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+boardslide',
    points: 15,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Tailslide',
    description: 'Sliding the tail of the board.',
    imageUrl: 'https://picsum.photos/seed/Tailslide/600/600',
    difficulty: 'Advanced',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+tailslide',
    points: 35,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Noseslide',
    description: 'Sliding the nose of the board.',
    imageUrl: 'https://picsum.photos/seed/Noseslide/600/600',
    difficulty: 'Intermediate',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+noseslide',
    points: 20,
    prerequisites: ['Ollie'],
    isPublic: true,
  },
  {
    name: 'Bluntslide',
    description: 'Sliding the tail with the wheels on top of the ledge.',
    imageUrl: 'https://picsum.photos/seed/Bluntslide/600/600',
    difficulty: 'Advanced',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+bluntslide',
    points: 50,
    prerequisites: ['Tailslide'],
    isPublic: true,
  },
  {
    name: 'Darkslide',
    description: 'Sliding on the grip tape side of the board.',
    imageUrl: 'https://picsum.photos/seed/Darkslide/600/600',
    difficulty: 'Advanced',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+darkslide',
    points: 70,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Powerslide',
    description: 'Turning the board 90 degrees to slide the wheels and slow down.',
    imageUrl: 'https://picsum.photos/seed/Powerslide/600/600',
    difficulty: 'Easy',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+powerslide',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },

  // --- TRANSITION ---
  {
    name: 'Rock to Fakie',
    description: 'Stalling the middle of the board on the coping and coming back down.',
    imageUrl: 'https://picsum.photos/seed/RockToFakie/600/600',
    difficulty: 'Easy',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+rock+to+fakie',
    points: 15,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Axle Stall',
    description: 'Stalling on both trucks on top of the coping.',
    imageUrl: 'https://picsum.photos/seed/AxleStall/600/600',
    difficulty: 'Intermediate',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+axle+stall',
    points: 20,
    prerequisites: ['Rock to Fakie', '50-50 Grind'],
    isPublic: true,
  },
  {
    name: 'Rock and Roll',
    description: 'Rock to fakie but pivoting 180 to come in forward.',
    imageUrl: 'https://picsum.photos/seed/RockAndRoll/600/600',
    difficulty: 'Intermediate',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+rock+and+roll+skate',
    points: 20,
    prerequisites: ['Rock to Fakie', 'Kickturn'],
    isPublic: true,
  },
  {
    name: 'Disaster',
    description: '180 ollie stalling the middle of the board on the coping.',
    imageUrl: 'https://picsum.photos/seed/Disaster/600/600',
    difficulty: 'Advanced',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+disaster+skate',
    points: 35,
    prerequisites: ['Rock and Roll', 'Ollie'],
    isPublic: true,
  },
  {
    name: 'Drop In',
    description: 'Entering a ramp from the top.',
    imageUrl: 'https://picsum.photos/seed/DropIn/600/600',
    difficulty: 'Easy',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+drop+in+skate',
    points: 10,
    prerequisites: [],
    isPublic: true,
  },

  // --- OLD SCHOOL / FREESTYLE ---
  {
    name: 'Casper',
    description: 'Balancing upside down on the tail and front foot.',
    imageUrl: 'https://picsum.photos/seed/Casper/600/600',
    difficulty: 'Advanced',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+casper+skate',
    points: 40,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Primo',
    description: 'Balancing on the side edge of the board.',
    imageUrl: 'https://picsum.photos/seed/Primo/600/600',
    difficulty: 'Advanced',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+primo+stall',
    points: 50,
    prerequisites: [],
    isPublic: true,
  },
  {
    name: 'Fingerflip',
    description: 'Flipping the board with your hand while jumping.',
    imageUrl: 'https://picsum.photos/seed/Fingerflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip', // Categorizing as Flip makes sense here
    video_url: 'https://www.youtube.com/results?search_query=how+to+fingerflip',
    points: 25,
    prerequisites: [],
    isPublic: true,
  },
];
