import { TrickMeta } from '@/types';

export const INITIAL_TRICKS: TrickMeta[] = [
  // Basics & Foundation
  {
    name: 'Ollie',
    description: 'The fundamental jump. Popping the tail and sliding the front foot up to level the board.',
    imageUrl: 'https://picsum.photos/seed/Ollie/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+ollie',
    points: 10,
    prerequisites: [],
  },
  {
    name: 'Manual',
    description: 'Balancing on the back two wheels while rolling.',
    imageUrl: 'https://picsum.photos/seed/Manual/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+manual+skateboard',
    points: 10,
    prerequisites: [],
  },
  {
    name: 'Kickturn',
    description: 'Lifting the front wheels to pivot and turn.',
    imageUrl: 'https://picsum.photos/seed/Kickturn/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+kickturn',
    points: 5,
    prerequisites: [],
  },
  {
    name: 'Tic-Tac',
    description: 'Consecutive kickturns to generate speed.',
    imageUrl: 'https://picsum.photos/seed/Tic-Tac/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+tictac+skateboard',
    points: 5,
    prerequisites: [],
  },
  {
    name: 'Fakie Riding',
    description: 'Riding backwards in your normal stance.',
    imageUrl: 'https://picsum.photos/seed/Fakie/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+ride+fakie',
    points: 10,
    prerequisites: [],
  },
  {
    name: 'Switch Riding',
    description: 'Riding in your opposite stance.',
    imageUrl: 'https://picsum.photos/seed/Switch/600/600',
    difficulty: 'Advanced',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+ride+switch',
    points: 50,
    prerequisites: [],
  },
  {
    name: 'Shuvit',
    description: 'Rotating the board 180 degrees horizontally without popping the tail.',
    imageUrl: 'https://picsum.photos/seed/Shuvit/600/600',
    difficulty: 'Easy',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+shuvit',
    points: 15,
    prerequisites: [],
  },
  {
    name: 'Pop Shuvit',
    description: 'Popping the tail to rotate the board 180 degrees horizontally in the air.',
    imageUrl: 'https://picsum.photos/seed/PopShuvit/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+pop+shuvit',
    points: 20,
    prerequisites: ['Ollie', 'Shuvit'],
  },
  {
    name: 'Frontside 180',
    description: 'Rotating yourself and the board 180 degrees facing forward.',
    imageUrl: 'https://picsum.photos/seed/Frontside180/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+frontside+180',
    points: 20,
    prerequisites: ['Ollie'],
  },
  {
    name: 'Backside 180',
    description: 'Rotating yourself and the board 180 degrees facing backward.',
    imageUrl: 'https://picsum.photos/seed/Backside180/600/600',
    difficulty: 'Intermediate',
    category: 'Basics',
    video_url: 'https://www.youtube.com/results?search_query=how+to+backside+180',
    points: 25,
    prerequisites: ['Ollie'],
  },

  // Flip Tricks
  {
    name: 'Kickflip',
    description: 'Flipping the board 360 degrees along its axis with your toe.',
    imageUrl: 'https://picsum.photos/seed/Kickflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+kickflip',
    points: 30,
    prerequisites: ['Ollie'],
  },
  {
    name: 'Heelflip',
    description: 'Flipping the board 360 degrees in the opposite direction with your heel.',
    imageUrl: 'https://picsum.photos/seed/Heelflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+heelflip',
    points: 30,
    prerequisites: ['Ollie'],
  },
  {
    name: 'Varial Kickflip',
    description: 'A combination of a backside pop shuvit and a kickflip.',
    imageUrl: 'https://picsum.photos/seed/VarialKickflip/600/600',
    difficulty: 'Intermediate',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+varial+kickflip',
    points: 35,
    prerequisites: ['Kickflip', 'Pop Shuvit'],
  },
  {
    name: 'Hardflip',
    description: 'A frontside pop shuvit combined with a kickflip.',
    imageUrl: 'https://picsum.photos/seed/Hardflip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+hardflip',
    points: 50,
    prerequisites: ['Kickflip', 'Frontside 180'],
  },
  {
    name: '360 Flip (Tre Flip)',
    description: 'A 360 shove-it combined with a kickflip.',
    imageUrl: 'https://picsum.photos/seed/TreFlip/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+tre+flip',
    points: 60,
    prerequisites: ['Kickflip', 'Pop Shuvit', 'Varial Kickflip'],
  },
  {
    name: 'Impossible',
    description: 'Wrapping the board vertically around the back foot.',
    imageUrl: 'https://picsum.photos/seed/Impossible/600/600',
    difficulty: 'Advanced',
    category: 'Flip',
    video_url: 'https://www.youtube.com/results?search_query=how+to+impossible+trick',
    points: 55,
    prerequisites: ['360 Flip'],
  },

  // Grinds & Slides
  {
    name: '50-50 Grind',
    description: 'Grinding on both trucks equally.',
    imageUrl: 'https://picsum.photos/seed/5050Grind/600/600',
    difficulty: 'Intermediate',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+50-50+grind',
    points: 25,
    prerequisites: ['Ollie'],
  },
  {
    name: '5-0 Grind',
    description: 'Grinding only on the back truck.',
    imageUrl: 'https://picsum.photos/seed/5-0Grind/600/600',
    difficulty: 'Intermediate',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+5-0+grind',
    points: 30,
    prerequisites: ['50-50 Grind', 'Manual'],
  },
  {
    name: 'Nose Grind',
    description: 'Grinding only on the front truck.',
    imageUrl: 'https://picsum.photos/seed/NoseGrind/600/600',
    difficulty: 'Advanced',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+nose+grind',
    points: 40,
    prerequisites: ['50-50 Grind'],
  },
  {
    name: 'Boardslide',
    description: 'Sliding the middle of the board between the trucks.',
    imageUrl: 'https://picsum.photos/seed/Boardslide/600/600',
    difficulty: 'Easy',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+boardslide',
    points: 15,
    prerequisites: ['Ollie'],
  },
  {
    name: 'Noseslide',
    description: 'Sliding on the nose of the deck.',
    imageUrl: 'https://picsum.photos/seed/Noseslide/600/600',
    difficulty: 'Intermediate',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+noseslide',
    points: 20,
    prerequisites: ['Ollie'],
  },
  {
    name: 'Tailslide',
    description: 'Sliding on the tail of the deck.',
    imageUrl: 'https://picsum.photos/seed/Tailslide/600/600',
    difficulty: 'Advanced',
    category: 'Slide',
    video_url: 'https://www.youtube.com/results?search_query=how+to+tailslide',
    points: 35,
    prerequisites: ['Ollie'],
  },
  {
    name: 'Crooked Grind',
    description: 'Grinding on the front truck with the nose angled out.',
    imageUrl: 'https://picsum.photos/seed/CrookedGrind/600/600',
    difficulty: 'Advanced',
    category: 'Grind',
    video_url: 'https://www.youtube.com/results?search_query=how+to+crooked+grind',
    points: 45,
    prerequisites: ['Noseslide', 'Nose Grind'],
  },

  // Transition
  {
    name: 'Rock to Fakie',
    description: 'Hooking the front truck over the coping and rolling back fakie.',
    imageUrl: 'https://picsum.photos/seed/RockToFakie/600/600',
    difficulty: 'Easy',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+rock+to+fakie',
    points: 15,
    prerequisites: [],
  },
  {
    name: 'Drop In',
    description: 'Entering a bowl or ramp from the top coping.',
    imageUrl: 'https://picsum.photos/seed/DropIn/600/600',
    difficulty: 'Easy',
    category: 'Transition',
    video_url: 'https://www.youtube.com/results?search_query=how+to+drop+in+skateboard',
    points: 10,
    prerequisites: [],
  },
];
